name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build-release:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: sentinel-linux
            asset_name: sentinel-x86_64-unknown-linux-gnu

          - os: macos-latest
            artifact_name: sentinel-mac
            asset_name: sentinel-x86_64-apple-darwin

          - os: windows-latest
            artifact_name: sentinel.exe
            asset_name: sentinel-x86_64-pc-windows-msvc.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release --locked --manifest-path=sentinel-app/Cargo.toml

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ matrix.os == 'windows-latest' && 'target/release/sentinel-app.exe' || 'target/release/sentinel-app' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
